[package]
name = "todo_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.4.10"
rocket_contrib = { version = "0.4.10", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"



